name: quick_send
description: Send money in the quickest way
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  retrofit: ^4.7.2
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  auto_route: ^10.1.0
  logger: ^2.5.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  retrofit_generator: ^10.0.2
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true
